In [ ]:
%run train.py

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Training from step: 477 
INFO:tensorflow:Step #477: rate 0.001000, accuracy 15.0%, cross entropy 2.566057
INFO:tensorflow:Step #478: rate 0.001000, accuracy 7.0%, cross entropy 2.631460
INFO:tensorflow:Step #479: rate 0.001000, accuracy 10.0%, cross entropy 2.543553
INFO:tensorflow:Step #480: rate 0.001000, accuracy 17.0%, cross entropy 2.511765
INFO:tensorflow:Step #481: rate 0.001000, accuracy 6.0%, cross entropy 2.576101
INFO:tensorflow:Step #482: rate 0.001000, accuracy 10.0%, cross entropy 2.567875
INFO:tensorflow:Step #483: rate 0.001000, accuracy 11.0%, cross entropy 2.559705
INFO:tensorflow:Step #484: rate 0.001000, accuracy 14.0%, cross

INFO:tensorflow:Step #561: rate 0.001000, accuracy 16.0%, cross entropy 2.452666
INFO:tensorflow:Step #562: rate 0.001000, accuracy 14.0%, cross entropy 2.440606
INFO:tensorflow:Step #563: rate 0.001000, accuracy 13.0%, cross entropy 2.466356
INFO:tensorflow:Step #564: rate 0.001000, accuracy 13.0%, cross entropy 2.466927
INFO:tensorflow:Step #565: rate 0.001000, accuracy 13.0%, cross entropy 2.457849
INFO:tensorflow:Step #566: rate 0.001000, accuracy 12.0%, cross entropy 2.451004
INFO:tensorflow:Step #567: rate 0.001000, accuracy 14.0%, cross entropy 2.483054
INFO:tensorflow:Step #568: rate 0.001000, accuracy 11.0%, cross entropy 2.466742
INFO:tensorflow:Step #569: rate 0.001000, accuracy 10.0%, cross entropy 2.464091
INFO:tensorflow:Step #570: rate 0.001000, accuracy 16.0%, cross entropy 2.479016
INFO:tensorflow:Step #571: rate 0.001000, accuracy 16.0%, cross entropy 2.400192
INFO:tensorflow:Step #572: rate 0.001000, accuracy 9.0%, cross entropy 2.484691
INFO:tensorflow:Step #573: ra

INFO:tensorflow:Step #662: rate 0.001000, accuracy 20.0%, cross entropy 2.373262
INFO:tensorflow:Step #663: rate 0.001000, accuracy 17.0%, cross entropy 2.448360
INFO:tensorflow:Step #664: rate 0.001000, accuracy 23.0%, cross entropy 2.382470
INFO:tensorflow:Step #665: rate 0.001000, accuracy 14.0%, cross entropy 2.399393
INFO:tensorflow:Step #666: rate 0.001000, accuracy 13.0%, cross entropy 2.431246
INFO:tensorflow:Step #667: rate 0.001000, accuracy 22.0%, cross entropy 2.402139
INFO:tensorflow:Step #668: rate 0.001000, accuracy 19.0%, cross entropy 2.394345
INFO:tensorflow:Step #669: rate 0.001000, accuracy 14.0%, cross entropy 2.416905
INFO:tensorflow:Step #670: rate 0.001000, accuracy 14.0%, cross entropy 2.387549
INFO:tensorflow:Step #671: rate 0.001000, accuracy 12.0%, cross entropy 2.407730
INFO:tensorflow:Step #672: rate 0.001000, accuracy 16.0%, cross entropy 2.430713
INFO:tensorflow:Step #673: rate 0.001000, accuracy 18.0%, cross entropy 2.429030
INFO:tensorflow:Step #674: r

INFO:tensorflow:Step #763: rate 0.001000, accuracy 19.0%, cross entropy 2.353331
INFO:tensorflow:Step #764: rate 0.001000, accuracy 15.0%, cross entropy 2.370081
INFO:tensorflow:Step #765: rate 0.001000, accuracy 23.0%, cross entropy 2.300210
INFO:tensorflow:Step #766: rate 0.001000, accuracy 21.0%, cross entropy 2.336552
INFO:tensorflow:Step #767: rate 0.001000, accuracy 16.0%, cross entropy 2.394402
INFO:tensorflow:Step #768: rate 0.001000, accuracy 14.0%, cross entropy 2.380426
INFO:tensorflow:Step #769: rate 0.001000, accuracy 15.0%, cross entropy 2.384036
INFO:tensorflow:Step #770: rate 0.001000, accuracy 18.0%, cross entropy 2.297320
INFO:tensorflow:Step #771: rate 0.001000, accuracy 13.0%, cross entropy 2.370320
INFO:tensorflow:Step #772: rate 0.001000, accuracy 14.0%, cross entropy 2.375380
INFO:tensorflow:Step #773: rate 0.001000, accuracy 23.0%, cross entropy 2.343247
INFO:tensorflow:Step #774: rate 0.001000, accuracy 19.0%, cross entropy 2.372368
INFO:tensorflow:Step #775: r

INFO:tensorflow:Step #855: rate 0.001000, accuracy 31.0%, cross entropy 2.300058
INFO:tensorflow:Step #856: rate 0.001000, accuracy 24.0%, cross entropy 2.325098
INFO:tensorflow:Step #857: rate 0.001000, accuracy 21.0%, cross entropy 2.318670
INFO:tensorflow:Step #858: rate 0.001000, accuracy 24.0%, cross entropy 2.246338
INFO:tensorflow:Step #859: rate 0.001000, accuracy 24.0%, cross entropy 2.290287
INFO:tensorflow:Step #860: rate 0.001000, accuracy 14.0%, cross entropy 2.338243
INFO:tensorflow:Step #861: rate 0.001000, accuracy 17.0%, cross entropy 2.338982
INFO:tensorflow:Step #862: rate 0.001000, accuracy 20.0%, cross entropy 2.337284
INFO:tensorflow:Step #863: rate 0.001000, accuracy 16.0%, cross entropy 2.371589
INFO:tensorflow:Step #864: rate 0.001000, accuracy 16.0%, cross entropy 2.239182
INFO:tensorflow:Step #865: rate 0.001000, accuracy 16.0%, cross entropy 2.351423
INFO:tensorflow:Step #866: rate 0.001000, accuracy 25.0%, cross entropy 2.332063
INFO:tensorflow:Step #867: r

INFO:tensorflow:Step #956: rate 0.001000, accuracy 29.0%, cross entropy 2.286382
INFO:tensorflow:Step #957: rate 0.001000, accuracy 21.0%, cross entropy 2.250157
INFO:tensorflow:Step #958: rate 0.001000, accuracy 14.0%, cross entropy 2.410590
INFO:tensorflow:Step #959: rate 0.001000, accuracy 27.0%, cross entropy 2.252519
INFO:tensorflow:Step #960: rate 0.001000, accuracy 20.0%, cross entropy 2.246022
INFO:tensorflow:Step #961: rate 0.001000, accuracy 20.0%, cross entropy 2.257943
INFO:tensorflow:Step #962: rate 0.001000, accuracy 29.0%, cross entropy 2.197817
INFO:tensorflow:Step #963: rate 0.001000, accuracy 25.0%, cross entropy 2.244901
INFO:tensorflow:Step #964: rate 0.001000, accuracy 24.0%, cross entropy 2.186621
INFO:tensorflow:Step #965: rate 0.001000, accuracy 26.0%, cross entropy 2.230012
INFO:tensorflow:Step #966: rate 0.001000, accuracy 24.0%, cross entropy 2.315058
INFO:tensorflow:Step #967: rate 0.001000, accuracy 21.0%, cross entropy 2.242894
INFO:tensorflow:Step #968: r

INFO:tensorflow:Step #1052: rate 0.001000, accuracy 31.0%, cross entropy 2.130846
INFO:tensorflow:Step #1053: rate 0.001000, accuracy 29.0%, cross entropy 2.147902
INFO:tensorflow:Step #1054: rate 0.001000, accuracy 28.0%, cross entropy 2.126168
INFO:tensorflow:Step #1055: rate 0.001000, accuracy 25.0%, cross entropy 2.131507
INFO:tensorflow:Step #1056: rate 0.001000, accuracy 32.0%, cross entropy 2.159651
INFO:tensorflow:Step #1057: rate 0.001000, accuracy 30.0%, cross entropy 2.177626
INFO:tensorflow:Step #1058: rate 0.001000, accuracy 24.0%, cross entropy 2.159415
INFO:tensorflow:Step #1059: rate 0.001000, accuracy 31.0%, cross entropy 2.160580
INFO:tensorflow:Step #1060: rate 0.001000, accuracy 22.0%, cross entropy 2.371574
INFO:tensorflow:Step #1061: rate 0.001000, accuracy 39.0%, cross entropy 2.042687
INFO:tensorflow:Step #1062: rate 0.001000, accuracy 37.0%, cross entropy 2.090005
INFO:tensorflow:Step #1063: rate 0.001000, accuracy 24.0%, cross entropy 2.182743
INFO:tensorflow:

INFO:tensorflow:Step #1152: rate 0.001000, accuracy 31.0%, cross entropy 2.121664
INFO:tensorflow:Step #1153: rate 0.001000, accuracy 29.0%, cross entropy 2.098708
INFO:tensorflow:Step #1154: rate 0.001000, accuracy 28.0%, cross entropy 2.060912
INFO:tensorflow:Step #1155: rate 0.001000, accuracy 29.0%, cross entropy 2.135662
INFO:tensorflow:Step #1156: rate 0.001000, accuracy 35.0%, cross entropy 2.027293
INFO:tensorflow:Step #1157: rate 0.001000, accuracy 33.0%, cross entropy 2.056793
INFO:tensorflow:Step #1158: rate 0.001000, accuracy 29.0%, cross entropy 2.029788
INFO:tensorflow:Step #1159: rate 0.001000, accuracy 33.0%, cross entropy 2.063838
INFO:tensorflow:Step #1160: rate 0.001000, accuracy 29.0%, cross entropy 2.099879
INFO:tensorflow:Step #1161: rate 0.001000, accuracy 32.0%, cross entropy 2.138987
INFO:tensorflow:Step #1162: rate 0.001000, accuracy 29.0%, cross entropy 2.009356
INFO:tensorflow:Step #1163: rate 0.001000, accuracy 24.0%, cross entropy 2.097823
INFO:tensorflow:

INFO:tensorflow:Step #1243: rate 0.001000, accuracy 47.0%, cross entropy 1.822829
INFO:tensorflow:Step #1244: rate 0.001000, accuracy 33.0%, cross entropy 2.052701
INFO:tensorflow:Step #1245: rate 0.001000, accuracy 29.0%, cross entropy 2.136840
INFO:tensorflow:Step #1246: rate 0.001000, accuracy 37.0%, cross entropy 1.900445
INFO:tensorflow:Step #1247: rate 0.001000, accuracy 32.0%, cross entropy 1.921428
INFO:tensorflow:Step #1248: rate 0.001000, accuracy 33.0%, cross entropy 1.977186
INFO:tensorflow:Step #1249: rate 0.001000, accuracy 33.0%, cross entropy 1.951523
INFO:tensorflow:Step #1250: rate 0.001000, accuracy 37.0%, cross entropy 2.008939
INFO:tensorflow:Step #1251: rate 0.001000, accuracy 34.0%, cross entropy 2.001183
INFO:tensorflow:Step #1252: rate 0.001000, accuracy 39.0%, cross entropy 1.886199
INFO:tensorflow:Step #1253: rate 0.001000, accuracy 32.0%, cross entropy 2.127099
INFO:tensorflow:Step #1254: rate 0.001000, accuracy 33.0%, cross entropy 1.953372
INFO:tensorflow:

INFO:tensorflow:Step #1343: rate 0.001000, accuracy 42.0%, cross entropy 1.753437
INFO:tensorflow:Step #1344: rate 0.001000, accuracy 37.0%, cross entropy 1.833964
INFO:tensorflow:Step #1345: rate 0.001000, accuracy 31.0%, cross entropy 1.974224
INFO:tensorflow:Step #1346: rate 0.001000, accuracy 37.0%, cross entropy 1.842285
INFO:tensorflow:Step #1347: rate 0.001000, accuracy 40.0%, cross entropy 1.838924
INFO:tensorflow:Step #1348: rate 0.001000, accuracy 42.0%, cross entropy 1.796165
INFO:tensorflow:Step #1349: rate 0.001000, accuracy 42.0%, cross entropy 1.830503
INFO:tensorflow:Step #1350: rate 0.001000, accuracy 28.0%, cross entropy 2.091527
INFO:tensorflow:Step #1351: rate 0.001000, accuracy 37.0%, cross entropy 1.858184
INFO:tensorflow:Step #1352: rate 0.001000, accuracy 41.0%, cross entropy 1.862232
INFO:tensorflow:Step #1353: rate 0.001000, accuracy 36.0%, cross entropy 1.898205
INFO:tensorflow:Step #1354: rate 0.001000, accuracy 41.0%, cross entropy 1.869421
INFO:tensorflow:

INFO:tensorflow:Step #1443: rate 0.001000, accuracy 37.0%, cross entropy 1.776339
INFO:tensorflow:Step #1444: rate 0.001000, accuracy 45.0%, cross entropy 1.728903
INFO:tensorflow:Step #1445: rate 0.001000, accuracy 42.0%, cross entropy 1.744844
INFO:tensorflow:Step #1446: rate 0.001000, accuracy 39.0%, cross entropy 1.800001
INFO:tensorflow:Step #1447: rate 0.001000, accuracy 33.0%, cross entropy 1.879260
INFO:tensorflow:Step #1448: rate 0.001000, accuracy 38.0%, cross entropy 1.826061
INFO:tensorflow:Step #1449: rate 0.001000, accuracy 39.0%, cross entropy 1.898059
INFO:tensorflow:Step #1450: rate 0.001000, accuracy 36.0%, cross entropy 1.871870
INFO:tensorflow:Step #1451: rate 0.001000, accuracy 40.0%, cross entropy 1.802834
INFO:tensorflow:Step #1452: rate 0.001000, accuracy 40.0%, cross entropy 1.797816
INFO:tensorflow:Step #1453: rate 0.001000, accuracy 41.0%, cross entropy 1.844022
INFO:tensorflow:Step #1454: rate 0.001000, accuracy 40.0%, cross entropy 1.882533
INFO:tensorflow:

INFO:tensorflow:Step #1543: rate 0.001000, accuracy 32.0%, cross entropy 1.770122
INFO:tensorflow:Step #1544: rate 0.001000, accuracy 43.0%, cross entropy 1.815950
INFO:tensorflow:Step #1545: rate 0.001000, accuracy 45.0%, cross entropy 1.743911
INFO:tensorflow:Step #1546: rate 0.001000, accuracy 46.0%, cross entropy 1.784401
INFO:tensorflow:Step #1547: rate 0.001000, accuracy 47.0%, cross entropy 1.605553
INFO:tensorflow:Step #1548: rate 0.001000, accuracy 38.0%, cross entropy 1.926731
INFO:tensorflow:Step #1549: rate 0.001000, accuracy 37.0%, cross entropy 1.890031
INFO:tensorflow:Step #1550: rate 0.001000, accuracy 42.0%, cross entropy 1.689998
INFO:tensorflow:Step #1551: rate 0.001000, accuracy 33.0%, cross entropy 1.779075
INFO:tensorflow:Step #1552: rate 0.001000, accuracy 34.0%, cross entropy 1.923789
INFO:tensorflow:Step #1553: rate 0.001000, accuracy 52.0%, cross entropy 1.747378
INFO:tensorflow:Step #1554: rate 0.001000, accuracy 48.0%, cross entropy 1.698872
INFO:tensorflow:

INFO:tensorflow:Step #1634: rate 0.001000, accuracy 36.0%, cross entropy 1.821448
INFO:tensorflow:Step #1635: rate 0.001000, accuracy 42.0%, cross entropy 1.676781
INFO:tensorflow:Step #1636: rate 0.001000, accuracy 36.0%, cross entropy 1.773167
INFO:tensorflow:Step #1637: rate 0.001000, accuracy 41.0%, cross entropy 1.633291
INFO:tensorflow:Step #1638: rate 0.001000, accuracy 34.0%, cross entropy 1.819391
INFO:tensorflow:Step #1639: rate 0.001000, accuracy 49.0%, cross entropy 1.611663
INFO:tensorflow:Step #1640: rate 0.001000, accuracy 48.0%, cross entropy 1.646152
INFO:tensorflow:Step #1641: rate 0.001000, accuracy 41.0%, cross entropy 1.761752
INFO:tensorflow:Step #1642: rate 0.001000, accuracy 39.0%, cross entropy 1.733944
INFO:tensorflow:Step #1643: rate 0.001000, accuracy 43.0%, cross entropy 1.734446
INFO:tensorflow:Step #1644: rate 0.001000, accuracy 35.0%, cross entropy 1.840198
INFO:tensorflow:Step #1645: rate 0.001000, accuracy 32.0%, cross entropy 1.972201
INFO:tensorflow:

INFO:tensorflow:Step #1734: rate 0.001000, accuracy 50.0%, cross entropy 1.485367
INFO:tensorflow:Step #1735: rate 0.001000, accuracy 45.0%, cross entropy 1.755505
INFO:tensorflow:Step #1736: rate 0.001000, accuracy 46.0%, cross entropy 1.661783
INFO:tensorflow:Step #1737: rate 0.001000, accuracy 34.0%, cross entropy 1.822956
INFO:tensorflow:Step #1738: rate 0.001000, accuracy 45.0%, cross entropy 1.792348
INFO:tensorflow:Step #1739: rate 0.001000, accuracy 37.0%, cross entropy 1.711778
INFO:tensorflow:Step #1740: rate 0.001000, accuracy 36.0%, cross entropy 1.774389
INFO:tensorflow:Step #1741: rate 0.001000, accuracy 37.0%, cross entropy 1.859365
INFO:tensorflow:Step #1742: rate 0.001000, accuracy 47.0%, cross entropy 1.741220
INFO:tensorflow:Step #1743: rate 0.001000, accuracy 43.0%, cross entropy 1.647160
INFO:tensorflow:Step #1744: rate 0.001000, accuracy 44.0%, cross entropy 1.664752
INFO:tensorflow:Step #1745: rate 0.001000, accuracy 46.0%, cross entropy 1.579266
INFO:tensorflow:

INFO:tensorflow:Step #1834: rate 0.001000, accuracy 39.0%, cross entropy 1.789105
INFO:tensorflow:Step #1835: rate 0.001000, accuracy 43.0%, cross entropy 1.801325
INFO:tensorflow:Step #1836: rate 0.001000, accuracy 46.0%, cross entropy 1.686002
INFO:tensorflow:Step #1837: rate 0.001000, accuracy 39.0%, cross entropy 1.669556
INFO:tensorflow:Step #1838: rate 0.001000, accuracy 59.0%, cross entropy 1.308344
INFO:tensorflow:Step #1839: rate 0.001000, accuracy 46.0%, cross entropy 1.700604
INFO:tensorflow:Step #1840: rate 0.001000, accuracy 48.0%, cross entropy 1.651659
INFO:tensorflow:Step #1841: rate 0.001000, accuracy 53.0%, cross entropy 1.559392
INFO:tensorflow:Step #1842: rate 0.001000, accuracy 55.0%, cross entropy 1.641471
INFO:tensorflow:Step #1843: rate 0.001000, accuracy 58.0%, cross entropy 1.410201
INFO:tensorflow:Step #1844: rate 0.001000, accuracy 45.0%, cross entropy 1.707966
INFO:tensorflow:Step #1845: rate 0.001000, accuracy 43.0%, cross entropy 1.788675
INFO:tensorflow:

INFO:tensorflow:Step #1934: rate 0.001000, accuracy 38.0%, cross entropy 1.795238
INFO:tensorflow:Step #1935: rate 0.001000, accuracy 45.0%, cross entropy 1.661647
INFO:tensorflow:Step #1936: rate 0.001000, accuracy 47.0%, cross entropy 1.572994
INFO:tensorflow:Step #1937: rate 0.001000, accuracy 41.0%, cross entropy 1.729734
INFO:tensorflow:Step #1938: rate 0.001000, accuracy 43.0%, cross entropy 1.677100
INFO:tensorflow:Step #1939: rate 0.001000, accuracy 41.0%, cross entropy 1.729241
INFO:tensorflow:Step #1940: rate 0.001000, accuracy 34.0%, cross entropy 1.704397
INFO:tensorflow:Step #1941: rate 0.001000, accuracy 58.0%, cross entropy 1.593942
INFO:tensorflow:Step #1942: rate 0.001000, accuracy 53.0%, cross entropy 1.460606
INFO:tensorflow:Step #1943: rate 0.001000, accuracy 47.0%, cross entropy 1.541095
INFO:tensorflow:Step #1944: rate 0.001000, accuracy 49.0%, cross entropy 1.607579
INFO:tensorflow:Step #1945: rate 0.001000, accuracy 42.0%, cross entropy 1.676064
INFO:tensorflow:

INFO:tensorflow:Step #2025: rate 0.001000, accuracy 40.0%, cross entropy 1.720171
INFO:tensorflow:Step #2026: rate 0.001000, accuracy 54.0%, cross entropy 1.535183
INFO:tensorflow:Step #2027: rate 0.001000, accuracy 52.0%, cross entropy 1.489622
INFO:tensorflow:Step #2028: rate 0.001000, accuracy 49.0%, cross entropy 1.504809
INFO:tensorflow:Step #2029: rate 0.001000, accuracy 45.0%, cross entropy 1.544435
INFO:tensorflow:Step #2030: rate 0.001000, accuracy 44.0%, cross entropy 1.608572
INFO:tensorflow:Step #2031: rate 0.001000, accuracy 51.0%, cross entropy 1.408194
INFO:tensorflow:Step #2032: rate 0.001000, accuracy 48.0%, cross entropy 1.593230
INFO:tensorflow:Step #2033: rate 0.001000, accuracy 43.0%, cross entropy 1.589138
INFO:tensorflow:Step #2034: rate 0.001000, accuracy 43.0%, cross entropy 1.523299
INFO:tensorflow:Step #2035: rate 0.001000, accuracy 53.0%, cross entropy 1.570827
INFO:tensorflow:Step #2036: rate 0.001000, accuracy 48.0%, cross entropy 1.632106
INFO:tensorflow:

INFO:tensorflow:Step #2125: rate 0.001000, accuracy 47.0%, cross entropy 1.563298
INFO:tensorflow:Step #2126: rate 0.001000, accuracy 55.0%, cross entropy 1.438859
INFO:tensorflow:Step #2127: rate 0.001000, accuracy 47.0%, cross entropy 1.543528
INFO:tensorflow:Step #2128: rate 0.001000, accuracy 41.0%, cross entropy 1.684632
INFO:tensorflow:Step #2129: rate 0.001000, accuracy 42.0%, cross entropy 1.593383
INFO:tensorflow:Step #2130: rate 0.001000, accuracy 46.0%, cross entropy 1.590221
INFO:tensorflow:Step #2131: rate 0.001000, accuracy 50.0%, cross entropy 1.420417
INFO:tensorflow:Step #2132: rate 0.001000, accuracy 55.0%, cross entropy 1.480049
INFO:tensorflow:Step #2133: rate 0.001000, accuracy 50.0%, cross entropy 1.632197
INFO:tensorflow:Step #2134: rate 0.001000, accuracy 61.0%, cross entropy 1.218777
INFO:tensorflow:Step #2135: rate 0.001000, accuracy 46.0%, cross entropy 1.636408
INFO:tensorflow:Step #2136: rate 0.001000, accuracy 46.0%, cross entropy 1.499931
INFO:tensorflow:

INFO:tensorflow:Step #2225: rate 0.001000, accuracy 38.0%, cross entropy 1.743394
INFO:tensorflow:Step #2226: rate 0.001000, accuracy 48.0%, cross entropy 1.677839
INFO:tensorflow:Step #2227: rate 0.001000, accuracy 55.0%, cross entropy 1.436686
INFO:tensorflow:Step #2228: rate 0.001000, accuracy 52.0%, cross entropy 1.604169
INFO:tensorflow:Step #2229: rate 0.001000, accuracy 60.0%, cross entropy 1.378958
INFO:tensorflow:Step #2230: rate 0.001000, accuracy 47.0%, cross entropy 1.555166
INFO:tensorflow:Step #2231: rate 0.001000, accuracy 55.0%, cross entropy 1.484770
INFO:tensorflow:Step #2232: rate 0.001000, accuracy 61.0%, cross entropy 1.372175
INFO:tensorflow:Step #2233: rate 0.001000, accuracy 50.0%, cross entropy 1.524880
INFO:tensorflow:Step #2234: rate 0.001000, accuracy 49.0%, cross entropy 1.475212
INFO:tensorflow:Step #2235: rate 0.001000, accuracy 50.0%, cross entropy 1.491619
INFO:tensorflow:Step #2236: rate 0.001000, accuracy 40.0%, cross entropy 1.668518
INFO:tensorflow:

INFO:tensorflow:Step #2325: rate 0.001000, accuracy 51.0%, cross entropy 1.419132
INFO:tensorflow:Step #2326: rate 0.001000, accuracy 44.0%, cross entropy 1.526501
INFO:tensorflow:Step #2327: rate 0.001000, accuracy 55.0%, cross entropy 1.301025
INFO:tensorflow:Step #2328: rate 0.001000, accuracy 56.0%, cross entropy 1.438740
INFO:tensorflow:Step #2329: rate 0.001000, accuracy 41.0%, cross entropy 1.570110
INFO:tensorflow:Step #2330: rate 0.001000, accuracy 55.0%, cross entropy 1.451256
INFO:tensorflow:Step #2331: rate 0.001000, accuracy 48.0%, cross entropy 1.423958
INFO:tensorflow:Step #2332: rate 0.001000, accuracy 59.0%, cross entropy 1.188333
INFO:tensorflow:Step #2333: rate 0.001000, accuracy 47.0%, cross entropy 1.445699
INFO:tensorflow:Step #2334: rate 0.001000, accuracy 51.0%, cross entropy 1.556098
INFO:tensorflow:Step #2335: rate 0.001000, accuracy 50.0%, cross entropy 1.464863
INFO:tensorflow:Step #2336: rate 0.001000, accuracy 43.0%, cross entropy 1.645714
INFO:tensorflow:

INFO:tensorflow:Step #2416: rate 0.001000, accuracy 52.0%, cross entropy 1.386279
INFO:tensorflow:Step #2417: rate 0.001000, accuracy 54.0%, cross entropy 1.373364
INFO:tensorflow:Step #2418: rate 0.001000, accuracy 48.0%, cross entropy 1.538858
INFO:tensorflow:Step #2419: rate 0.001000, accuracy 54.0%, cross entropy 1.273926
INFO:tensorflow:Step #2420: rate 0.001000, accuracy 59.0%, cross entropy 1.187719
INFO:tensorflow:Step #2421: rate 0.001000, accuracy 52.0%, cross entropy 1.547255
INFO:tensorflow:Step #2422: rate 0.001000, accuracy 60.0%, cross entropy 1.209569
INFO:tensorflow:Step #2423: rate 0.001000, accuracy 60.0%, cross entropy 1.390513
INFO:tensorflow:Step #2424: rate 0.001000, accuracy 48.0%, cross entropy 1.645302
INFO:tensorflow:Step #2425: rate 0.001000, accuracy 60.0%, cross entropy 1.353168
INFO:tensorflow:Step #2426: rate 0.001000, accuracy 54.0%, cross entropy 1.332537
INFO:tensorflow:Step #2427: rate 0.001000, accuracy 55.0%, cross entropy 1.332344
INFO:tensorflow:

INFO:tensorflow:Step #2516: rate 0.001000, accuracy 54.0%, cross entropy 1.429109
INFO:tensorflow:Step #2517: rate 0.001000, accuracy 54.0%, cross entropy 1.390476
INFO:tensorflow:Step #2518: rate 0.001000, accuracy 63.0%, cross entropy 1.248696
INFO:tensorflow:Step #2519: rate 0.001000, accuracy 58.0%, cross entropy 1.334068
INFO:tensorflow:Step #2520: rate 0.001000, accuracy 61.0%, cross entropy 1.270069
INFO:tensorflow:Step #2521: rate 0.001000, accuracy 54.0%, cross entropy 1.342938
INFO:tensorflow:Step #2522: rate 0.001000, accuracy 62.0%, cross entropy 1.228627
INFO:tensorflow:Step #2523: rate 0.001000, accuracy 56.0%, cross entropy 1.255397
INFO:tensorflow:Step #2524: rate 0.001000, accuracy 60.0%, cross entropy 1.305462
INFO:tensorflow:Step #2525: rate 0.001000, accuracy 50.0%, cross entropy 1.328650
INFO:tensorflow:Step #2526: rate 0.001000, accuracy 53.0%, cross entropy 1.520805
INFO:tensorflow:Step #2527: rate 0.001000, accuracy 47.0%, cross entropy 1.503693
INFO:tensorflow:

INFO:tensorflow:Step #2616: rate 0.001000, accuracy 54.0%, cross entropy 1.315919
INFO:tensorflow:Step #2617: rate 0.001000, accuracy 44.0%, cross entropy 1.647742
INFO:tensorflow:Step #2618: rate 0.001000, accuracy 56.0%, cross entropy 1.431646
INFO:tensorflow:Step #2619: rate 0.001000, accuracy 65.0%, cross entropy 1.203137
INFO:tensorflow:Step #2620: rate 0.001000, accuracy 55.0%, cross entropy 1.349671
INFO:tensorflow:Step #2621: rate 0.001000, accuracy 55.0%, cross entropy 1.459095
INFO:tensorflow:Step #2622: rate 0.001000, accuracy 51.0%, cross entropy 1.307575
INFO:tensorflow:Step #2623: rate 0.001000, accuracy 50.0%, cross entropy 1.350890
INFO:tensorflow:Step #2624: rate 0.001000, accuracy 64.0%, cross entropy 1.213232
INFO:tensorflow:Step #2625: rate 0.001000, accuracy 63.0%, cross entropy 1.217031
INFO:tensorflow:Step #2626: rate 0.001000, accuracy 55.0%, cross entropy 1.371028
INFO:tensorflow:Step #2627: rate 0.001000, accuracy 61.0%, cross entropy 1.223190
INFO:tensorflow:

INFO:tensorflow:Step #2716: rate 0.001000, accuracy 52.0%, cross entropy 1.360659
INFO:tensorflow:Step #2717: rate 0.001000, accuracy 57.0%, cross entropy 1.217815
INFO:tensorflow:Step #2718: rate 0.001000, accuracy 57.0%, cross entropy 1.236915
INFO:tensorflow:Step #2719: rate 0.001000, accuracy 57.0%, cross entropy 1.255336
INFO:tensorflow:Step #2720: rate 0.001000, accuracy 49.0%, cross entropy 1.451337
INFO:tensorflow:Step #2721: rate 0.001000, accuracy 58.0%, cross entropy 1.188936
INFO:tensorflow:Step #2722: rate 0.001000, accuracy 62.0%, cross entropy 1.166044
INFO:tensorflow:Step #2723: rate 0.001000, accuracy 51.0%, cross entropy 1.420731
INFO:tensorflow:Step #2724: rate 0.001000, accuracy 52.0%, cross entropy 1.345884
INFO:tensorflow:Step #2725: rate 0.001000, accuracy 56.0%, cross entropy 1.228967
INFO:tensorflow:Step #2726: rate 0.001000, accuracy 58.0%, cross entropy 1.308197
INFO:tensorflow:Step #2727: rate 0.001000, accuracy 62.0%, cross entropy 1.242726
INFO:tensorflow:

INFO:tensorflow:Step #2807: rate 0.001000, accuracy 53.0%, cross entropy 1.299267
INFO:tensorflow:Step #2808: rate 0.001000, accuracy 62.0%, cross entropy 1.192675
INFO:tensorflow:Step #2809: rate 0.001000, accuracy 63.0%, cross entropy 1.196805
INFO:tensorflow:Step #2810: rate 0.001000, accuracy 65.0%, cross entropy 1.179991
INFO:tensorflow:Step #2811: rate 0.001000, accuracy 52.0%, cross entropy 1.341366
INFO:tensorflow:Step #2812: rate 0.001000, accuracy 58.0%, cross entropy 1.220540
INFO:tensorflow:Step #2813: rate 0.001000, accuracy 63.0%, cross entropy 1.208456
INFO:tensorflow:Step #2814: rate 0.001000, accuracy 54.0%, cross entropy 1.333660
INFO:tensorflow:Step #2815: rate 0.001000, accuracy 53.0%, cross entropy 1.306834
INFO:tensorflow:Step #2816: rate 0.001000, accuracy 57.0%, cross entropy 1.242586
INFO:tensorflow:Step #2817: rate 0.001000, accuracy 58.0%, cross entropy 1.212962
INFO:tensorflow:Step #2818: rate 0.001000, accuracy 53.0%, cross entropy 1.261599
INFO:tensorflow:

INFO:tensorflow:Step #2907: rate 0.001000, accuracy 64.0%, cross entropy 1.122820
INFO:tensorflow:Step #2908: rate 0.001000, accuracy 63.0%, cross entropy 1.147798
INFO:tensorflow:Step #2909: rate 0.001000, accuracy 49.0%, cross entropy 1.318994
INFO:tensorflow:Step #2910: rate 0.001000, accuracy 59.0%, cross entropy 1.328168
INFO:tensorflow:Step #2911: rate 0.001000, accuracy 59.0%, cross entropy 1.180126
INFO:tensorflow:Step #2912: rate 0.001000, accuracy 63.0%, cross entropy 1.161794
INFO:tensorflow:Step #2913: rate 0.001000, accuracy 63.0%, cross entropy 1.088391
INFO:tensorflow:Step #2914: rate 0.001000, accuracy 58.0%, cross entropy 1.287462
INFO:tensorflow:Step #2915: rate 0.001000, accuracy 57.0%, cross entropy 1.307202
INFO:tensorflow:Step #2916: rate 0.001000, accuracy 61.0%, cross entropy 1.351851
INFO:tensorflow:Step #2917: rate 0.001000, accuracy 56.0%, cross entropy 1.393791
INFO:tensorflow:Step #2918: rate 0.001000, accuracy 57.0%, cross entropy 1.320387
INFO:tensorflow:

INFO:tensorflow:Step #3007: rate 0.001000, accuracy 53.0%, cross entropy 1.436743
INFO:tensorflow:Step #3008: rate 0.001000, accuracy 61.0%, cross entropy 1.132436
INFO:tensorflow:Step #3009: rate 0.001000, accuracy 59.0%, cross entropy 1.140001
INFO:tensorflow:Step #3010: rate 0.001000, accuracy 61.0%, cross entropy 1.184834
INFO:tensorflow:Step #3011: rate 0.001000, accuracy 64.0%, cross entropy 1.240338
INFO:tensorflow:Step #3012: rate 0.001000, accuracy 66.0%, cross entropy 1.170901
INFO:tensorflow:Step #3013: rate 0.001000, accuracy 54.0%, cross entropy 1.302638
INFO:tensorflow:Step #3014: rate 0.001000, accuracy 57.0%, cross entropy 1.267120
INFO:tensorflow:Step #3015: rate 0.001000, accuracy 73.0%, cross entropy 0.947522
INFO:tensorflow:Step #3016: rate 0.001000, accuracy 53.0%, cross entropy 1.376871
INFO:tensorflow:Step #3017: rate 0.001000, accuracy 59.0%, cross entropy 1.248828
INFO:tensorflow:Step #3018: rate 0.001000, accuracy 58.0%, cross entropy 1.264676
INFO:tensorflow:

INFO:tensorflow:Step #3107: rate 0.001000, accuracy 64.0%, cross entropy 1.118423
INFO:tensorflow:Step #3108: rate 0.001000, accuracy 62.0%, cross entropy 1.096189
INFO:tensorflow:Step #3109: rate 0.001000, accuracy 67.0%, cross entropy 1.016876
INFO:tensorflow:Step #3110: rate 0.001000, accuracy 68.0%, cross entropy 0.963388
INFO:tensorflow:Step #3111: rate 0.001000, accuracy 60.0%, cross entropy 1.245504
INFO:tensorflow:Step #3112: rate 0.001000, accuracy 61.0%, cross entropy 1.228689
INFO:tensorflow:Step #3113: rate 0.001000, accuracy 66.0%, cross entropy 1.118800
INFO:tensorflow:Step #3114: rate 0.001000, accuracy 64.0%, cross entropy 1.298162
INFO:tensorflow:Step #3115: rate 0.001000, accuracy 72.0%, cross entropy 1.077929
INFO:tensorflow:Step #3116: rate 0.001000, accuracy 60.0%, cross entropy 1.215656
INFO:tensorflow:Step #3117: rate 0.001000, accuracy 50.0%, cross entropy 1.463369
INFO:tensorflow:Step #3118: rate 0.001000, accuracy 68.0%, cross entropy 0.981976
INFO:tensorflow:

INFO:tensorflow:Step 3200: Validation accuracy = 69.2% (N=4445)
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-3200"
INFO:tensorflow:Step #3201: rate 0.001000, accuracy 64.0%, cross entropy 1.072795
INFO:tensorflow:Step #3202: rate 0.001000, accuracy 64.0%, cross entropy 1.085733
INFO:tensorflow:Step #3203: rate 0.001000, accuracy 61.0%, cross entropy 1.132207
INFO:tensorflow:Step #3204: rate 0.001000, accuracy 62.0%, cross entropy 1.234759
INFO:tensorflow:Step #3205: rate 0.001000, accuracy 65.0%, cross entropy 1.200685
INFO:tensorflow:Step #3206: rate 0.001000, accuracy 59.0%, cross entropy 1.162064
INFO:tensorflow:Step #3207: rate 0.001000, accuracy 64.0%, cross entropy 0.995028
INFO:tensorflow:Step #3208: rate 0.001000, accuracy 63.0%, cross entropy 1.215010
INFO:tensorflow:Step #3209: rate 0.001000, accuracy 65.0%, cross entropy 1.102828
INFO:tensorflow:Step #3210: rate 0.001000, accuracy 65.0%, cross entropy 1.094943
INFO:tensorflow:Step #3211: rate 0.001000, acc

INFO:tensorflow:Step #3300: rate 0.001000, accuracy 61.0%, cross entropy 1.150034
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-3300"
INFO:tensorflow:Step #3301: rate 0.001000, accuracy 60.0%, cross entropy 1.213890
INFO:tensorflow:Step #3302: rate 0.001000, accuracy 61.0%, cross entropy 1.163718
INFO:tensorflow:Step #3303: rate 0.001000, accuracy 62.0%, cross entropy 1.194353
INFO:tensorflow:Step #3304: rate 0.001000, accuracy 67.0%, cross entropy 0.942033
INFO:tensorflow:Step #3305: rate 0.001000, accuracy 61.0%, cross entropy 1.050812
INFO:tensorflow:Step #3306: rate 0.001000, accuracy 61.0%, cross entropy 1.224425
INFO:tensorflow:Step #3307: rate 0.001000, accuracy 57.0%, cross entropy 1.172868
INFO:tensorflow:Step #3308: rate 0.001000, accuracy 58.0%, cross entropy 1.227054
INFO:tensorflow:Step #3309: rate 0.001000, accuracy 66.0%, cross entropy 1.074891
INFO:tensorflow:Step #3310: rate 0.001000, accuracy 63.0%, cross entropy 1.172861
INFO:tensorflow:Step #3311: 

INFO:tensorflow:Step #3400: rate 0.001000, accuracy 67.0%, cross entropy 1.193200
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-3400"
INFO:tensorflow:Step #3401: rate 0.001000, accuracy 59.0%, cross entropy 1.227576
INFO:tensorflow:Step #3402: rate 0.001000, accuracy 63.0%, cross entropy 1.251108
INFO:tensorflow:Step #3403: rate 0.001000, accuracy 64.0%, cross entropy 1.069692
INFO:tensorflow:Step #3404: rate 0.001000, accuracy 67.0%, cross entropy 1.017329
INFO:tensorflow:Step #3405: rate 0.001000, accuracy 59.0%, cross entropy 1.145752
INFO:tensorflow:Step #3406: rate 0.001000, accuracy 62.0%, cross entropy 1.153031
INFO:tensorflow:Step #3407: rate 0.001000, accuracy 69.0%, cross entropy 1.089766
INFO:tensorflow:Step #3408: rate 0.001000, accuracy 72.0%, cross entropy 1.111269
INFO:tensorflow:Step #3409: rate 0.001000, accuracy 61.0%, cross entropy 1.163272
INFO:tensorflow:Step #3410: rate 0.001000, accuracy 64.0%, cross entropy 1.106703
INFO:tensorflow:Step #3411: 

INFO:tensorflow:Step #3500: rate 0.001000, accuracy 62.0%, cross entropy 1.180540
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-3500"
INFO:tensorflow:Step #3501: rate 0.001000, accuracy 59.0%, cross entropy 1.098169
INFO:tensorflow:Step #3502: rate 0.001000, accuracy 61.0%, cross entropy 1.068215
INFO:tensorflow:Step #3503: rate 0.001000, accuracy 67.0%, cross entropy 0.970684
INFO:tensorflow:Step #3504: rate 0.001000, accuracy 61.0%, cross entropy 1.206965
INFO:tensorflow:Step #3505: rate 0.001000, accuracy 58.0%, cross entropy 1.149150
INFO:tensorflow:Step #3506: rate 0.001000, accuracy 62.0%, cross entropy 1.176562
INFO:tensorflow:Step #3507: rate 0.001000, accuracy 59.0%, cross entropy 1.221461
INFO:tensorflow:Step #3508: rate 0.001000, accuracy 66.0%, cross entropy 0.973658
INFO:tensorflow:Step #3509: rate 0.001000, accuracy 72.0%, cross entropy 0.893848
INFO:tensorflow:Step #3510: rate 0.001000, accuracy 61.0%, cross entropy 1.143470
INFO:tensorflow:Step #3511: 

INFO:tensorflow:Step #3600: rate 0.001000, accuracy 62.0%, cross entropy 1.119323
INFO:tensorflow:Confusion Matrix:
 [[366   1   1   0   1   0   0   1   0   0   1   0]
 [  3 156  21  17  20  22  26  22  22   8  16  38]
 [  4  17 307  26   3   5  27   0   0   0   1   7]
 [  0   8   4 254   9  32  13   0   1   1  16  68]
 [  4   3   1   7 272   3  15   2   3   2  33   5]
 [  3   7   3  34   3 288   4   0   3   0  12  20]
 [  3   7  29   6  15   2 269  14   0   0   4   3]
 [  5   9   1   3   7   1  29 301   3   1   2   1]
 [  3  14   0   1  21   4   2   6 278  16  10   8]
 [  7   2   0   1  90   0  10   7  30 204  17   5]
 [  3   5   1   3  48   9   6   0   1   1 262  11]
 [  2  11   1  65   7  29   1   2   2   1  10 241]]
INFO:tensorflow:Step 3600: Validation accuracy = 71.9% (N=4445)
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-3600"
INFO:tensorflow:Step #3601: rate 0.001000, accuracy 57.0%, cross entropy 1.166404
INFO:tensorflow:Step #3602: rate 0.001000, accuracy 70

INFO:tensorflow:Step #3691: rate 0.001000, accuracy 64.0%, cross entropy 1.038449
INFO:tensorflow:Step #3692: rate 0.001000, accuracy 65.0%, cross entropy 0.947849
INFO:tensorflow:Step #3693: rate 0.001000, accuracy 67.0%, cross entropy 1.104366
INFO:tensorflow:Step #3694: rate 0.001000, accuracy 58.0%, cross entropy 1.289099
INFO:tensorflow:Step #3695: rate 0.001000, accuracy 63.0%, cross entropy 0.950484
INFO:tensorflow:Step #3696: rate 0.001000, accuracy 63.0%, cross entropy 1.134887
INFO:tensorflow:Step #3697: rate 0.001000, accuracy 67.0%, cross entropy 0.991763
INFO:tensorflow:Step #3698: rate 0.001000, accuracy 65.0%, cross entropy 0.904844
INFO:tensorflow:Step #3699: rate 0.001000, accuracy 64.0%, cross entropy 1.147238
INFO:tensorflow:Step #3700: rate 0.001000, accuracy 77.0%, cross entropy 0.959674
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-3700"
INFO:tensorflow:Step #3701: rate 0.001000, accuracy 58.0%, cross entropy 1.245809
INFO:tensorflow:Step #3702: 

INFO:tensorflow:Step #3791: rate 0.001000, accuracy 65.0%, cross entropy 1.001835
INFO:tensorflow:Step #3792: rate 0.001000, accuracy 63.0%, cross entropy 1.041475
INFO:tensorflow:Step #3793: rate 0.001000, accuracy 69.0%, cross entropy 1.055675
INFO:tensorflow:Step #3794: rate 0.001000, accuracy 69.0%, cross entropy 0.985202
INFO:tensorflow:Step #3795: rate 0.001000, accuracy 58.0%, cross entropy 1.117166
INFO:tensorflow:Step #3796: rate 0.001000, accuracy 67.0%, cross entropy 0.995342
INFO:tensorflow:Step #3797: rate 0.001000, accuracy 57.0%, cross entropy 1.208961
INFO:tensorflow:Step #3798: rate 0.001000, accuracy 64.0%, cross entropy 1.294166
INFO:tensorflow:Step #3799: rate 0.001000, accuracy 61.0%, cross entropy 1.145924
INFO:tensorflow:Step #3800: rate 0.001000, accuracy 67.0%, cross entropy 0.926401
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-3800"
INFO:tensorflow:Step #3801: rate 0.001000, accuracy 63.0%, cross entropy 1.104654
INFO:tensorflow:Step #3802: 

INFO:tensorflow:Step #3891: rate 0.001000, accuracy 62.0%, cross entropy 1.118981
INFO:tensorflow:Step #3892: rate 0.001000, accuracy 70.0%, cross entropy 0.942814
INFO:tensorflow:Step #3893: rate 0.001000, accuracy 69.0%, cross entropy 1.002467
INFO:tensorflow:Step #3894: rate 0.001000, accuracy 67.0%, cross entropy 0.960605
INFO:tensorflow:Step #3895: rate 0.001000, accuracy 68.0%, cross entropy 1.006932
INFO:tensorflow:Step #3896: rate 0.001000, accuracy 69.0%, cross entropy 1.032034
INFO:tensorflow:Step #3897: rate 0.001000, accuracy 71.0%, cross entropy 0.917275
INFO:tensorflow:Step #3898: rate 0.001000, accuracy 57.0%, cross entropy 1.245137
INFO:tensorflow:Step #3899: rate 0.001000, accuracy 71.0%, cross entropy 0.865442
INFO:tensorflow:Step #3900: rate 0.001000, accuracy 62.0%, cross entropy 1.173574
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-3900"
INFO:tensorflow:Step #3901: rate 0.001000, accuracy 73.0%, cross entropy 0.774624
INFO:tensorflow:Step #3902: 