In [1]:
%run train.py

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Training from step: 5330 
INFO:tensorflow:Step #5330: rate 0.001000, accuracy 7.0%, cross entropy 2.628154
INFO:tensorflow:Step #5331: rate 0.001000, accuracy 5.0%, cross entropy 2.625226
INFO:tensorflow:Step #5332: rate 0.001000, accuracy 10.0%, cross entropy 2.570671
INFO:tensorflow:Step #5333: rate 0.001000, accuracy 9.0%, cross entropy 2.463901
INFO:tensorflow:Step #5334: rate 0.001000, accuracy 8.0%, cross entropy 2.505569
INFO:tensorflow:Step #5335: rate 0.001000, accuracy 6.0%, cross entropy 2.563258
INFO:tensorflow:Step #5336: rate 0.001000, accuracy 2.0%, cross entropy 2.558566
INFO:tensorflow:Step #5337: rate 0.001000, accuracy 8.0%, c

INFO:tensorflow:Step #5413: rate 0.001000, accuracy 17.0%, cross entropy 2.481325
INFO:tensorflow:Step #5414: rate 0.001000, accuracy 11.0%, cross entropy 2.450849
INFO:tensorflow:Step #5415: rate 0.001000, accuracy 16.0%, cross entropy 2.512734
INFO:tensorflow:Step #5416: rate 0.001000, accuracy 7.0%, cross entropy 2.475169
INFO:tensorflow:Step #5417: rate 0.001000, accuracy 4.0%, cross entropy 2.480641
INFO:tensorflow:Step #5418: rate 0.001000, accuracy 16.0%, cross entropy 2.450441
INFO:tensorflow:Step #5419: rate 0.001000, accuracy 17.0%, cross entropy 2.426911
INFO:tensorflow:Step #5420: rate 0.001000, accuracy 14.0%, cross entropy 2.497674
INFO:tensorflow:Step #5421: rate 0.001000, accuracy 24.0%, cross entropy 2.407251
INFO:tensorflow:Step #5422: rate 0.001000, accuracy 13.0%, cross entropy 2.460135
INFO:tensorflow:Step #5423: rate 0.001000, accuracy 7.0%, cross entropy 2.497151
INFO:tensorflow:Step #5424: rate 0.001000, accuracy 8.0%, cross entropy 2.488052
INFO:tensorflow:Step

INFO:tensorflow:Step #5513: rate 0.001000, accuracy 15.0%, cross entropy 2.410193
INFO:tensorflow:Step #5514: rate 0.001000, accuracy 15.0%, cross entropy 2.424905
INFO:tensorflow:Step #5515: rate 0.001000, accuracy 13.0%, cross entropy 2.443306
INFO:tensorflow:Step #5516: rate 0.001000, accuracy 6.0%, cross entropy 2.468914
INFO:tensorflow:Step #5517: rate 0.001000, accuracy 15.0%, cross entropy 2.463431
INFO:tensorflow:Step #5518: rate 0.001000, accuracy 17.0%, cross entropy 2.399038
INFO:tensorflow:Step #5519: rate 0.001000, accuracy 16.0%, cross entropy 2.427944
INFO:tensorflow:Step #5520: rate 0.001000, accuracy 15.0%, cross entropy 2.508474
INFO:tensorflow:Step #5521: rate 0.001000, accuracy 14.0%, cross entropy 2.414124
INFO:tensorflow:Step #5522: rate 0.001000, accuracy 22.0%, cross entropy 2.311614
INFO:tensorflow:Step #5523: rate 0.001000, accuracy 16.0%, cross entropy 2.417705
INFO:tensorflow:Step #5524: rate 0.001000, accuracy 19.0%, cross entropy 2.376448
INFO:tensorflow:S

INFO:tensorflow:Step #5604: rate 0.001000, accuracy 14.0%, cross entropy 2.402832
INFO:tensorflow:Step #5605: rate 0.001000, accuracy 13.0%, cross entropy 2.368354
INFO:tensorflow:Step #5606: rate 0.001000, accuracy 16.0%, cross entropy 2.338124
INFO:tensorflow:Step #5607: rate 0.001000, accuracy 15.0%, cross entropy 2.410399
INFO:tensorflow:Step #5608: rate 0.001000, accuracy 17.0%, cross entropy 2.352645
INFO:tensorflow:Step #5609: rate 0.001000, accuracy 13.0%, cross entropy 2.398290
INFO:tensorflow:Step #5610: rate 0.001000, accuracy 21.0%, cross entropy 2.374602
INFO:tensorflow:Step #5611: rate 0.001000, accuracy 19.0%, cross entropy 2.386230
INFO:tensorflow:Step #5612: rate 0.001000, accuracy 17.0%, cross entropy 2.378795
INFO:tensorflow:Step #5613: rate 0.001000, accuracy 13.0%, cross entropy 2.391707
INFO:tensorflow:Step #5614: rate 0.001000, accuracy 19.0%, cross entropy 2.363691
INFO:tensorflow:Step #5615: rate 0.001000, accuracy 12.0%, cross entropy 2.389176
INFO:tensorflow:

INFO:tensorflow:Step #5704: rate 0.001000, accuracy 22.0%, cross entropy 2.227933
INFO:tensorflow:Step #5705: rate 0.001000, accuracy 19.0%, cross entropy 2.329446
INFO:tensorflow:Step #5706: rate 0.001000, accuracy 16.0%, cross entropy 2.393560
INFO:tensorflow:Step #5707: rate 0.001000, accuracy 12.0%, cross entropy 2.373904
INFO:tensorflow:Step #5708: rate 0.001000, accuracy 16.0%, cross entropy 2.350079
INFO:tensorflow:Step #5709: rate 0.001000, accuracy 19.0%, cross entropy 2.356986
INFO:tensorflow:Step #5710: rate 0.001000, accuracy 18.0%, cross entropy 2.338154
INFO:tensorflow:Step #5711: rate 0.001000, accuracy 14.0%, cross entropy 2.418017
INFO:tensorflow:Step #5712: rate 0.001000, accuracy 20.0%, cross entropy 2.340652
INFO:tensorflow:Step #5713: rate 0.001000, accuracy 21.0%, cross entropy 2.362651
INFO:tensorflow:Step #5714: rate 0.001000, accuracy 22.0%, cross entropy 2.244523
INFO:tensorflow:Step #5715: rate 0.001000, accuracy 24.0%, cross entropy 2.339449
INFO:tensorflow:

INFO:tensorflow:Step #5804: rate 0.001000, accuracy 18.0%, cross entropy 2.339046
INFO:tensorflow:Step #5805: rate 0.001000, accuracy 23.0%, cross entropy 2.271792
INFO:tensorflow:Step #5806: rate 0.001000, accuracy 20.0%, cross entropy 2.319343
INFO:tensorflow:Step #5807: rate 0.001000, accuracy 17.0%, cross entropy 2.353541
INFO:tensorflow:Step #5808: rate 0.001000, accuracy 24.0%, cross entropy 2.178738
INFO:tensorflow:Step #5809: rate 0.001000, accuracy 26.0%, cross entropy 2.181335
INFO:tensorflow:Step #5810: rate 0.001000, accuracy 14.0%, cross entropy 2.340407
INFO:tensorflow:Step #5811: rate 0.001000, accuracy 19.0%, cross entropy 2.215268
INFO:tensorflow:Step #5812: rate 0.001000, accuracy 32.0%, cross entropy 2.279946
INFO:tensorflow:Step #5813: rate 0.001000, accuracy 20.0%, cross entropy 2.280623
INFO:tensorflow:Step #5814: rate 0.001000, accuracy 17.0%, cross entropy 2.224814
INFO:tensorflow:Step #5815: rate 0.001000, accuracy 17.0%, cross entropy 2.256438
INFO:tensorflow:

INFO:tensorflow:Step #5901: rate 0.001000, accuracy 20.0%, cross entropy 2.247404
INFO:tensorflow:Step #5902: rate 0.001000, accuracy 30.0%, cross entropy 2.168701
INFO:tensorflow:Step #5903: rate 0.001000, accuracy 25.0%, cross entropy 2.256720
INFO:tensorflow:Step #5904: rate 0.001000, accuracy 19.0%, cross entropy 2.194001
INFO:tensorflow:Step #5905: rate 0.001000, accuracy 22.0%, cross entropy 2.181552
INFO:tensorflow:Step #5906: rate 0.001000, accuracy 28.0%, cross entropy 2.145350
INFO:tensorflow:Step #5907: rate 0.001000, accuracy 25.0%, cross entropy 2.228986
INFO:tensorflow:Step #5908: rate 0.001000, accuracy 24.0%, cross entropy 2.196834
INFO:tensorflow:Step #5909: rate 0.001000, accuracy 31.0%, cross entropy 2.149039
INFO:tensorflow:Step #5910: rate 0.001000, accuracy 21.0%, cross entropy 2.232913
INFO:tensorflow:Step #5911: rate 0.001000, accuracy 29.0%, cross entropy 2.169992
INFO:tensorflow:Step #5912: rate 0.001000, accuracy 34.0%, cross entropy 2.142193
INFO:tensorflow:

INFO:tensorflow:Confusion Matrix:
 [[320   0   2   0  28   0   1   0   9  10   1   0]
 [ 14  41  33  69  18  53   0  14  15  18  19  77]
 [ 20  22 207  41  21  16   9  13   6  17  10  15]
 [ 10  22   6 138  12  47   4   3  25   7  10 122]
 [ 16   7   6  26  82  16   7   4  35  64  48  39]
 [ 15  16   6  48  10 155   1   3  56   9  14  44]
 [ 18  19  96  28  29  18  52  28  10  21   7  26]
 [ 15  27  44  55  12  20  36  66  13   8   6  61]
 [ 16   4   2  39  18  42   1   2 154  26  22  37]
 [ 21   1   5  20  55   9   6   3  67 130  40  16]
 [ 19   9  14  17  26  27   1   1  24  45 119  48]
 [ 10  16   7  83   6  32   1   3   5   3  22 184]]
INFO:tensorflow:Step 6000: Validation accuracy = 37.1% (N=4445)
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-6000"
INFO:tensorflow:Step #6001: rate 0.001000, accuracy 26.0%, cross entropy 2.137057
INFO:tensorflow:Step #6002: rate 0.001000, accuracy 19.0%, cross entropy 2.226147
INFO:tensorflow:Step #6003: rate 0.001000, accuracy 33

INFO:tensorflow:Step #6092: rate 0.001000, accuracy 33.0%, cross entropy 2.022714
INFO:tensorflow:Step #6093: rate 0.001000, accuracy 28.0%, cross entropy 2.225537
INFO:tensorflow:Step #6094: rate 0.001000, accuracy 24.0%, cross entropy 2.195069
INFO:tensorflow:Step #6095: rate 0.001000, accuracy 31.0%, cross entropy 2.031157
INFO:tensorflow:Step #6096: rate 0.001000, accuracy 37.0%, cross entropy 2.034293
INFO:tensorflow:Step #6097: rate 0.001000, accuracy 39.0%, cross entropy 1.998875
INFO:tensorflow:Step #6098: rate 0.001000, accuracy 31.0%, cross entropy 2.062500
INFO:tensorflow:Step #6099: rate 0.001000, accuracy 28.0%, cross entropy 2.107347
INFO:tensorflow:Step #6100: rate 0.001000, accuracy 36.0%, cross entropy 2.103926
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-6100"
INFO:tensorflow:Step #6101: rate 0.001000, accuracy 30.0%, cross entropy 2.095084
INFO:tensorflow:Step #6102: rate 0.001000, accuracy 25.0%, cross entropy 2.068163
INFO:tensorflow:Step #6103: 

INFO:tensorflow:Step #6192: rate 0.001000, accuracy 36.0%, cross entropy 1.997635
INFO:tensorflow:Step #6193: rate 0.001000, accuracy 38.0%, cross entropy 1.890270
INFO:tensorflow:Step #6194: rate 0.001000, accuracy 43.0%, cross entropy 1.917542
INFO:tensorflow:Step #6195: rate 0.001000, accuracy 36.0%, cross entropy 1.918163
INFO:tensorflow:Step #6196: rate 0.001000, accuracy 37.0%, cross entropy 1.951357
INFO:tensorflow:Step #6197: rate 0.001000, accuracy 28.0%, cross entropy 2.116399
INFO:tensorflow:Step #6198: rate 0.001000, accuracy 40.0%, cross entropy 2.050248
INFO:tensorflow:Step #6199: rate 0.001000, accuracy 36.0%, cross entropy 2.009410
INFO:tensorflow:Step #6200: rate 0.001000, accuracy 41.0%, cross entropy 1.863003
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-6200"
INFO:tensorflow:Step #6201: rate 0.001000, accuracy 38.0%, cross entropy 1.818532
INFO:tensorflow:Step #6202: rate 0.001000, accuracy 39.0%, cross entropy 1.970694
INFO:tensorflow:Step #6203: 

INFO:tensorflow:Step #6292: rate 0.001000, accuracy 42.0%, cross entropy 1.908680
INFO:tensorflow:Step #6293: rate 0.001000, accuracy 40.0%, cross entropy 1.828740
INFO:tensorflow:Step #6294: rate 0.001000, accuracy 40.0%, cross entropy 1.740563
INFO:tensorflow:Step #6295: rate 0.001000, accuracy 30.0%, cross entropy 2.033936
INFO:tensorflow:Step #6296: rate 0.001000, accuracy 30.0%, cross entropy 2.069703
INFO:tensorflow:Step #6297: rate 0.001000, accuracy 31.0%, cross entropy 1.935981
INFO:tensorflow:Step #6298: rate 0.001000, accuracy 43.0%, cross entropy 1.772447
INFO:tensorflow:Step #6299: rate 0.001000, accuracy 38.0%, cross entropy 1.949793
INFO:tensorflow:Step #6300: rate 0.001000, accuracy 47.0%, cross entropy 1.721043
INFO:tensorflow:Saving to "/tmp/speech_commands_train\conv.ckpt-6300"
INFO:tensorflow:Step #6301: rate 0.001000, accuracy 44.0%, cross entropy 1.816289
INFO:tensorflow:Step #6302: rate 0.001000, accuracy 29.0%, cross entropy 2.005627
INFO:tensorflow:Step #6303: 

INFO:tensorflow:Step #6392: rate 0.001000, accuracy 34.0%, cross entropy 1.904923
INFO:tensorflow:Step #6393: rate 0.001000, accuracy 42.0%, cross entropy 1.808175
INFO:tensorflow:Step #6394: rate 0.001000, accuracy 46.0%, cross entropy 1.781461
INFO:tensorflow:Step #6395: rate 0.001000, accuracy 47.0%, cross entropy 1.626573
INFO:tensorflow:Step #6396: rate 0.001000, accuracy 37.0%, cross entropy 1.820961
INFO:tensorflow:Step #6397: rate 0.001000, accuracy 40.0%, cross entropy 1.847451
INFO:tensorflow:Step #6398: rate 0.001000, accuracy 35.0%, cross entropy 1.918861
INFO:tensorflow:Step #6399: rate 0.001000, accuracy 35.0%, cross entropy 1.886312
INFO:tensorflow:Step #6400: rate 0.001000, accuracy 29.0%, cross entropy 1.981800
INFO:tensorflow:Confusion Matrix:
 [[342   0   4   0  21   0   1   0   1   1   1   0]
 [  9  71  79  33  21  53  12  23  17   8  15  30]
 [ 15  22 272  17   9  11  21  17   2   3   6   2]
 [  2  34   9 163  15  96  14  11  21   2  11  28]
 [ 11   5   6  14 167  

INFO:tensorflow:Step #6483: rate 0.001000, accuracy 36.0%, cross entropy 1.892966
INFO:tensorflow:Step #6484: rate 0.001000, accuracy 37.0%, cross entropy 1.806408
INFO:tensorflow:Step #6485: rate 0.001000, accuracy 39.0%, cross entropy 1.914676
INFO:tensorflow:Step #6486: rate 0.001000, accuracy 34.0%, cross entropy 1.816877
INFO:tensorflow:Step #6487: rate 0.001000, accuracy 46.0%, cross entropy 1.605638
INFO:tensorflow:Step #6488: rate 0.001000, accuracy 37.0%, cross entropy 1.854259
INFO:tensorflow:Step #6489: rate 0.001000, accuracy 35.0%, cross entropy 1.830592
INFO:tensorflow:Step #6490: rate 0.001000, accuracy 54.0%, cross entropy 1.622099
INFO:tensorflow:Step #6491: rate 0.001000, accuracy 49.0%, cross entropy 1.670580
INFO:tensorflow:Step #6492: rate 0.001000, accuracy 43.0%, cross entropy 1.723405
INFO:tensorflow:Step #6493: rate 0.001000, accuracy 42.0%, cross entropy 1.761765
INFO:tensorflow:Step #6494: rate 0.001000, accuracy 33.0%, cross entropy 1.850881
INFO:tensorflow:

INFO:tensorflow:Step #6583: rate 0.001000, accuracy 48.0%, cross entropy 1.665910
INFO:tensorflow:Step #6584: rate 0.001000, accuracy 49.0%, cross entropy 1.557048
INFO:tensorflow:Step #6585: rate 0.001000, accuracy 39.0%, cross entropy 1.915936
INFO:tensorflow:Step #6586: rate 0.001000, accuracy 47.0%, cross entropy 1.712415
INFO:tensorflow:Step #6587: rate 0.001000, accuracy 33.0%, cross entropy 1.845535
INFO:tensorflow:Step #6588: rate 0.001000, accuracy 41.0%, cross entropy 1.779604
INFO:tensorflow:Step #6589: rate 0.001000, accuracy 39.0%, cross entropy 1.606226
INFO:tensorflow:Step #6590: rate 0.001000, accuracy 43.0%, cross entropy 1.637552
INFO:tensorflow:Step #6591: rate 0.001000, accuracy 39.0%, cross entropy 1.680438
INFO:tensorflow:Step #6592: rate 0.001000, accuracy 52.0%, cross entropy 1.660180
INFO:tensorflow:Step #6593: rate 0.001000, accuracy 45.0%, cross entropy 1.606351
INFO:tensorflow:Step #6594: rate 0.001000, accuracy 46.0%, cross entropy 1.720655


KeyboardInterrupt: 